[workspace]
resolver = "2"

members = [
  "core_run_test",
  "alloc_run_test",
  "std_run_test",
]

exclude = [
  # stdarch has its own Cargo workspace
  "library/stdarch",
  "rust-src-patched/library/stdarch",
]
