[workspace]
members = [
  "core_sanity_test",
  "alloc_sanity_test",
  "std_sanity_test",
]

exclude = [
  # stdarch has its own Cargo workspace
  "library/stdarch",
  "rust-src-patched/library/stdarch",
]
